---

# Meta Variables
_scenario_name: scenario-8

# Role-specific Variables
project_name: "Demo"
project_url: "https://github.com/demonpig/aap-example-project"

event_stream_name: "54069451-2150-430b-b039-2685340ccb52"
