---
- name: Preparation - Build User Inventory
  hosts: localhost
  connection: local
  gather_facts: false
  # vars:
  #   num_users: 60
  #   batch_size: 10
  tasks:

    - name: Set scenarios list fact
      ansible.builtin.set_fact:
        scenarios_list: "{{ (playbook_dir + '/roles/') | list_scenarios }}"
        num_users: "{{ num_users | default(60) }}"
        batch_size: "{{ batch_size | default(10) }}"

    - name: Create in-memory hosts for parallel execution
      ansible.builtin.add_host:
        name: "user{{ item }}"
        groups: lab_users
      with_sequence: start=1 end="{{ num_users }}"

    - name: Deploy cluster-scoped operator
      ansible.builtin.include_role:
        name: operator

- name: Parallel Deployment by Scenario
  hosts: lab_users
  connection: local
  gather_facts: false
  serial: "{{ hostvars['localhost']['batch_size'] }}"
  tasks:
    - name: Execute deployment for each scenario
      ansible.builtin.include_tasks: process_scenario.yml
      loop: "{{ hostvars['localhost']['scenarios_list'] }}"
      loop_control:
        loop_var: current_scenario

- name: Pipeline Summary
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Print Execution Summary
      ansible.builtin.debug:
        msg: |-
          =========================================
          EXECUTION SUMMARY
          =========================================
          Action Performed: DEPLOY
          Total Users Processed: {{ groups['lab_users'] | length }}
          Total Scenarios Processed: {{ scenarios_list | length }}
          Total Namespaces Targeted: {{ (groups['lab_users'] | length) * (scenarios_list | length) }}
          =========================================