---
- name: Set iteration facts
  ansible.builtin.set_fact:
    # inventory_hostname represents the user_id (e.g., user1, user2)
    user_id: "{{ inventory_hostname }}"
    scenario_path: "{{ current_scenario.path }}"
    scenario_name: "{{ current_scenario.path | basename }}"

- name: Get scenario variables
  loop:
    - "{{ playbook_dir }}/{{ scenario_path }}/vars/operator.yml"
    - "{{ playbook_dir }}/{{ scenario_path }}/vars/main.yml"
  ansible.builtin.include_vars:
    file: "{{ item }}"
    hash_behaviour: replace

- name: Set project name fact
  ansible.builtin.set_fact:
    # Generates namespace: unique_id-scenario_name
    project_name: "{{ user_id }}-{{ _scenario_name }}"

- name: Setup namespace and operator
  ansible.builtin.include_role:
    name: operator

- name: Setup scenario
  ansible.builtin.include_role:
    name: "{{ scenario_name }}"