---

- name: Playbook Checks
  hosts: localhost
  connection: local
  gather_facts: false
  tags: ['always']

  vars:
    scenarios_list: "{{ (playbook_dir + '/roles/') | list_scenarios }}"

  vars_prompt:

    - name: student_ns
      private: no
      prompt: What is your assigned namespace name?

    - name: scenario_option
      private: no
      prompt: |-
        {% set scenarios = (playbook_dir + '/roles/') | list_scenarios %}
        {% for i in scenarios %}

        ID: {{ i.id }}
        Path: {{ i.path }}
        Description: {{ i.description }}
        {% endfor %}

        Enter the ID corresponding to your choice
    
    - name: break_fix
      private: no
      prompt: |- 
        Are you wanting to break or fix the scenario?
        Enter 'break' or 'fix' to proceed

  tasks:
    - name: Debug scenario_list variable
      ansible.builtin.debug:
        var: scenarios_list
        verbosity: 3

    - name: Get scenario metadata
      ansible.builtin.set_fact:
        scenario: "{{ scenarios_list | selectattr('id', 'equalto', scenario_option) | first | default({'path': '-'}) }}"

    - name: Check if selected scenario exists
      register: _scenario_role
      ansible.builtin.stat:
        path: "{{ playbook_dir }}/{{ scenario['path'] }}"

    - name: Print message if scenario not found
      when: not _scenario_role.stat.exists
      ansible.builtin.fail:
        msg: "Scenario #{{ scenario_option }} not found."

    - name: Get scenario variables
      loop:
        - "{{ playbook_dir }}/{{ scenario['path'] }}/vars/operator.yml"
        - "{{ playbook_dir }}/{{ scenario['path'] }}/vars/main.yml"
      ansible.builtin.include_vars:
        file: "{{ item }}"
        hash_behaviour: replace

    - name: Set scenario facts
      ansible.builtin.set_fact:
        # TODO: Rename these confusing variables

        # scenario_name will be the name of the role that lives within
        # the roles/ dir
        scenario_name: "{{ scenario.get('path') | basename }}"

        # _scenario_name is not to be confused with scenario_name. This private variable which can
        # be found in `vars/main.yml` of each role is used to define the namespace in which the
        # role will be operating within.
        #
        # There are some roles such as scenario_12 which enhance other scenarios such as scenario_1
        project_name: "{{student_ns}}-{{ _scenario_name }}"
        break_fix: "{{ break_fix }}"   

    - name: Break or fix?
      ansible.builtin.pause:
        prompt: |-
          We're about to {{ break_fix }} {{ scenario_name }}, are you sure?
          (yes or no)
          (Entering yes will {{ break_fix }} the lab. Enter no to cancel)
        echo: yes
      register: confirmation_input
      # until: confirmation_input.user_input is defined and confirmation_input.user_input | lower == 'yes'
      retries: 99999
      delay: 0        

    - name: fail if needed
      ansible.builtin.fail:
        msg: Not ready to proceed? Feel free to reach out to the instructors with questions
      when: confirmation_input.user_input != "yes"


- name: Scenario Setup Playbook
  hosts: all
  gather_facts: false
  tasks:
    - name: Set playbook variables
      tags: always
      ansible.builtin.set_fact:
        scenario_name: "{{ hostvars['localhost']['scenario_name'] }}"
        project_name: "{{ hostvars['localhost']['project_name'] }}"

    - name: Get scenario variables
      tags: always
      loop:
        - "{{ playbook_dir }}/roles/{{ scenario_name }}/vars/operator.yml"
        - "{{ playbook_dir }}/roles/{{ scenario_name }}/vars/main.yml"
      ansible.builtin.include_vars:
        file: "{{ item }}"
        hash_behaviour: replace     

    - name: Delete Block
      tags: ['never', 'delete']
      block:
        - name: Delete namespace {{ project_name }}
          kubernetes.core.k8s:
            api_version: project.openshift.io/v1
            kind: Project
            name: "{{ project_name }}"
            state: absent
            wait: yes
            wait_timeout: 300
            wait_sleep: 5
            wait_condition:
              type: Absent
              status: True

    - name: Deployment Block
      tags: ['never', 'deploy']
      block:
        - name: Setup namespace and operator
          ansible.builtin.include_role:
            name: operator

        - name: Setup scenario
          ansible.builtin.include_role:
            name: "{{ scenario_name }}"

    - name: Break Block
      # tags: ['never', 'break']
      block:
        - name: Break Scenario
          ansible.builtin.include_role:
            name: "{{ scenario_name }}"
            tasks_from: break.yml

        - name: Print Message
          ansible.builtin.debug:
            msg: "{{ _break_message | default('Have fun fixing!') }}"
      when: break_fix == "break"

    - name: Fix Block
      # tags: ['never', 'fix']
      block:
        - name: Fix Scenario
          ansible.builtin.include_role:
            name: "{{ scenario_name }}"
            tasks_from: fix.yml

        - name: Print Message
          ansible.builtin.debug:
            msg: "{{ _fix_message | default('All the problems have been resolved!') }}"
      when: break_fix == "fix"