---
- name: configure aap custom resource
  hosts: localhost
  tasks:

    - name: modify controller cr
      kubernetes.core.k8s:
        state: patched
        definition:
          apiVersion: aap.ansible.com/v1alpha1
          kind: AnsibleAutomationPlatform
          metadata:
            name: aap
            namespace: "{{ install_namespace }}"
          spec:
            database:      
              node_selector:
                "kubernetes.io/os": "not_linux"