---
- name: reset gateway operator and services
  hosts: localhost
  tasks:

  - name: Get Active CSV Name from Subscription
    kubernetes.core.k8s_info:
      api_version: operators.coreos.com/v1alpha1
      kind: Subscription
      # Use the name of your specific Subscription
      name: "ansible-automation-platform-operator" 
      namespace: "{{ install_namespace }}"
    register: sub_info

  - name: Set Active CSV Name fact
    ansible.builtin.set_fact:
      current_csv_name: "{{ sub_info.resources[0].status.currentCSV }}"

  - name: Revert CSV Patch Set Gateway Operator Replicas back to 1
    ansible.builtin.shell:
      cmd: >
        oc patch csv {{ current_csv_name }} -n {{ install_namespace }} --type='json' 
        -p='[{"op":"replace", "path":"/spec/install/spec/deployments/0/spec/replicas", "value":1}]'
    register: csv_revert_status
    changed_when: csv_revert_status.rc == 0 and ('patched' in csv_revert_status.stdout or 'patched' in csv_revert_status.stderr)
    failed_when: csv_revert_status.rc != 0

  - name: Get UID of the AnsibleAutomationPlatform CR
    kubernetes.core.k8s_info:
      api_version: aap.ansible.com/v1alpha1
      kind: AnsibleAutomationPlatform
      name: aap
      namespace: "{{ install_namespace }}"
    register: aap_cr_info    

  - name: Create the aap-postgres-15 Service
    kubernetes.core.k8s:
      api_version: v1
      kind: Service
      name: aap-postgres-15
      namespace: "{{ install_namespace }}" 
      state: present
      definition:
        apiVersion: v1
        kind: Service
        metadata:
          name: aap-postgres-15
          namespace: "{{ install_namespace }}" 
          ownerReferences:
            - apiVersion: aap.ansible.com/v1alpha1
              kind: AnsibleAutomationPlatform
              name: aap
              uid: "{{ aap_cr_info.resources[0].metadata.uid }}"
          labels:
            app.kubernetes.io/component: database
            app.kubernetes.io/instance: postgres-15-aap
            app.kubernetes.io/managed-by: aap-gateway-operator
            app.kubernetes.io/name: postgres-15
        spec:
          clusterIP: None
          ipFamilies:
            - IPv4
          ports:
            - name: '5432'
              protocol: TCP
              port: 5432
              targetPort: 5432
          internalTrafficPolicy: Cluster
          clusterIPs:
            - None
          type: ClusterIP
          ipFamilyPolicy: SingleStack
          sessionAffinity: None
          selector:
            app.kubernetes.io/component: database
            app.kubernetes.io/instance: postgres-15-aap
            app.kubernetes.io/managed-by: aap-gateway-operator
            app.kubernetes.io/name: postgres-15    