---
- name: configure aap custom resource
  hosts: localhost
  vars:
    wait_minutes: 5
    wait_delay_seconds: 15
  tasks:

    - name: Update AAP to latest operator
      kubernetes.core.k8s:
        state: patched
        definition:
          apiVersion: operators.coreos.com/v1alpha1
          kind: Subscription
          metadata:
            name: ansible-automation-platform-operator
            namespace: "{{ install_namespace }}"
          spec:
            channel: 'stable-2.5'
            installPlanApproval: Automatic
            name: ansible-automation-platform-operator
            source: redhat-operators
            sourceNamespace: openshift-marketplace

    - name: Get list of InstallPlans (Wait up to {{ wait_minutes }}m)
      kubernetes.core.k8s_info:
        api_version: operators.coreos.com/v1alpha1
        kind: InstallPlan
        namespace: "{{ install_namespace }}"
      register: install_plans_list
      until: install_plans_list.resources | length > 0
      retries: "{{ ((wait_minutes * 60) / wait_delay_seconds) | int }}"
      delay: "{{ wait_delay_seconds }}"
      failed_when: install_plans_list.resources | length == 0

    - name: Use OC to find the InstallPlan name for manual approval
      ansible.builtin.shell:
        cmd: "oc get installplan -n {{ install_namespace }} -o custom-columns=NAME:.metadata.name,PHASE:.status.phase --no-headers | grep 'RequiresApproval' | awk '{print $1}'"
      register: ip_cmd_output
      changed_when: false
      failed_when: ip_cmd_output.rc != 0 and 'No resources found' not in ip_cmd_output.stderr

    - name: Set final clean variable from command output
      ansible.builtin.set_fact:
        install_plan_name_final: "{{ ip_cmd_output.stdout | default('') | trim }}"

    - name: Verify extracted name and proceed to approve
      ansible.builtin.debug:
        msg: "FINAL CLEAN NAME: '{{ install_plan_name_final }}'. Proceeding to approve."
      when: install_plan_name_final is defined and install_plan_name_final | length > 0

    - name: Approve the identified InstallPlan using kubernetes.core
      kubernetes.core.k8s:
        state: patched
        api_version: operators.coreos.com/v1alpha1
        kind: InstallPlan
        name: "{{ install_plan_name_final }}" 
        namespace: "{{ install_namespace }}"
        definition:
          spec:
            approved: true
      when: install_plan_name_final is defined and install_plan_name_final | length > 0      