---
- name: update gateway password
  hosts: localhost
  tasks:

  - name: 1. Find the running aap-gateway pod name
    kubernetes.core.k8s_info:
      api_version: v1
      kind: Pod
      namespace: "{{ install_namespace }}"
      label_selectors: app.kubernetes.io/component=aap-gateway
    register: gateway_pods

  - name: Extract and Aggressively Clean the Name (Final List Conversion Fix)
    ansible.builtin.set_fact:
      extracted_name_raw: >
        {{ gateway_pods.resources 
          | selectattr('status.phase', 'equalto', 'Running') 
          | map(attribute='metadata.name')
          | first | default('') | string }}

  - name: remove newline
    ansible.builtin.set_fact:      
      gateway_pod_name: "{{ extracted_name_raw | replace('\n', '') | replace('\r', '') | trim }}"

  - name: debug
    ansible.builtin.debug:
      var: gateway_pod_name

  - name: Fail if gateway pod name was not found
    ansible.builtin.fail:
      msg: "Could not find a running pod with the label 'app=aap-gateway'. Check pod status."
    when: gateway_pod_name is none or gateway_pod_name | length == 0

  - name: Execute password change command with raw Python (Avoids getpass)
    kubernetes.core.k8s_exec:
      namespace: "{{ install_namespace }}"
      pod: "{{ gateway_pod_name }}"
      container: "api"
      command: >-
        bash -c "echo 'from django.contrib.auth import get_user_model; User = get_user_model(); u=User.objects.get(username=\"admin\"); u.set_password(\"h2as43d978hj\"); u.save()' | aap-gateway-manage shell"
    register: command_output
    changed_when: command_output.rc == 0

  - name: Display command output (check for 'None' or success)
    ansible.builtin.debug:
      var: command_output

  - name: Delete the aap-postgres-15 Route
    kubernetes.core.k8s:
      api_version: v1 
      kind: Service
      name: aap-postgres-15
      namespace: "{{ install_namespace }}" 
      state: absent
    register: route_delete_status

  - name: Verify Route Deletion Status
    ansible.builtin.debug:
      msg: "Route deleted successfully."
    when: route_delete_status.deleted is defined and route_delete_status.deleted