---
- name: configure hub
  hosts: localhost
  tasks:

    - name: Install Hub
      kubernetes.core.k8s:
        state: patched
        definition:
          apiVersion: aap.ansible.com/v1alpha1
          kind: AnsibleAutomationPlatform
          metadata:
            name: aap
            namespace: "{{ install_namespace }}"
          spec:
            hub:
              disabled: false
              content:
                resource_requirements:
                  limits:
                    cpu: 500m
                    memory: 800Mi
                  requests:
                    cpu: 100m
                    memory: 200Mi                    
              api:
                resource_requirements:
                  limits:
                    cpu: 1000m
                    memory: 1Gi
                  requests:
                    cpu: 400m
                    memory: 500Mi                          
              worker:
                resource_requirements:
                  limits:
                    cpu: 1000m
                    memory: 1Gi
                  requests:
                    cpu: 400m
                    memory: 500Mi                      

    # - name: Create AAP CR
    #   kubernetes.core.k8s:
    #     state: present
    #     definition:
    #       apiVersion: aap.ansible.com/v1alpha1
    #       kind: AnsibleAutomationPlatform
    #       metadata:
    #         name: aap
    #         namespace: "{{ install_namespace }}"
    #       spec:
    #         route_tls_termination_mechanism: Edge
    #         no_log: true
    #         redis_mode: standalone
    #         redis:
    #           resource_requirements:
    #             limits:
    #               cpu: 500m
    #               memory: 2Gi
    #             requests:
    #               cpu: 250m
    #               memory: 1Gi
    #         api:
    #           log_level: INFO
    #           replicas: 1
    #         database:
    #           postgres_data_volume_init: false
    #           idle_disabled: false
    #           resource_requirements:
    #             limits:
    #               cpu: 1000m
    #               memory: 100Mi
    #             requests:
    #               cpu: 500m
    #               memory: 50Mi
    #         controller:
    #           auto_upgrade: false