---
- name: configure aap custom resource
  hosts: localhost
  tasks:

    - name: modify controller cr
      kubernetes.core.k8s:
        state: patched
        definition:
          apiVersion: automationcontroller.ansible.com/v1beta1
          kind: AutomationController
          metadata:
            name: aap-controller
            namespace: "{{ aap_ns }}"
            patch:
              spec:
                auto_upgrade: true