---

- name: One Fish
  no_log: "{{ nolog | default(true) }}"
  register: _source_secret
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    name: "{{ secret_name }}"
    namespace: "{{ namespace}}"

- name: Two Fish
  no_log: "{{ nolog | default(true) }}"
  register: _source_secret_2
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    name: "{{ secret_name }}-2"
    namespace: "{{ namespace}}"

- name: Red Fish
  no_log: "{{ nolog | default(true) }}"
  when: _source_secret.resources | length > 0 and
        _source_secret_2.resources | length == 0
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ secret_name }}-2"
        namespace: "{{ namespace }}"
        labels: "{{ _source_secret.resources[0].metadata.labels | default({}) }}"
      type: "{{ _source_secret.resources[0].type }}"
      data: "{{ _source_secret.resources[0].data }}"

- name: Blue Fish
  no_log: "{{ nolog | default(true) }}"
  when: _source_secret.resources | length > 0
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ secret_name }}"
        namespace: "{{ namespace }}"
      stringData:
        secret_key: "whte_rbt.obj" # Let me know if you catch this reference
