---

- name: Set role variables
  ansible.builtin.include_vars:
    dir: "{{ role_path }}/vars"
    file: main.yml
    hash_behaviour: replace

- name: Create custom resource
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: automationcontroller.ansible.com/v1beta1
      kind: AutomationController
      metadata:
        name: "{{ _scenario_name }}-controller"
        namespace: "{{ namespace }}"
      spec:
        admin_user: admin
        auto_upgrade: true
        create_preload_data: true
        garbage_collect_secrets: false
        image_pull_policy: IfNotPresent
        ingress_type: Route
        ipv6_disabled: false
        loadbalancer_class: ''
        loadbalancer_ip: ''
        loadbalancer_port: 80
        loadbalancer_protocol: http
        metrics_utility_console_enabled: false
        metrics_utility_cronjob_gather_schedule: '@hourly'
        metrics_utility_cronjob_report_schedule: '@monthly'
        metrics_utility_enabled: false
        metrics_utility_pvc_claim_size: 5Gi
        no_log: true
        postgres_keepalives_count: 5
        postgres_keepalives_idle: 5
        postgres_keepalives_interval: 5
        postgres_keepalives: true
        postgres_resource_requirements:
          requests:
            cpu: 4
            memory: 4Gi
        projects_persistence: false
        projects_storage_access_mode: ReadWriteMany
        projects_storage_size: 8Gi
        replicas: 1
        route_tls_termination_mechanism: Edge
        set_self_labels: true
        task_liveness_failure_threshold: 3
        task_liveness_initial_delay: 5
        task_liveness_period: 0
        task_liveness_timeout: 1
        task_manage_replicas: true
        task_privileged: false
        task_readiness_failure_threshold: 3
        task_readiness_initial_delay: 20
        task_readiness_period: 0
        task_readiness_timeout: 1
        web_liveness_failure_threshold: 3
        web_liveness_initial_delay: 5
        web_liveness_period: 0
        web_liveness_timeout: 1
        web_manage_replicas: true
        web_readiness_failure_threshold: 3
        web_readiness_initial_delay: 20
        web_readiness_period: 0
        web_readiness_timeout: 1

  # Reference: https://github.com/ansible-automation-platform/aap-gateway-operator/blob/main/roles/ansibleautomationplatform/tasks/wait_for_controller.yml
- name: Wait for Automation Controller pod
  register: _controller_pod
  retries: 60
  delay: 15
  until:
    - _controller_pod['resources'] | length
    - _controller_pod['resources'][0].status.containerStatuses | selectattr('name', 'equalto', instance_name + '-controller-task') | map(attribute='ready') | list | first is defined
    - _controller_pod['resources'][0].status.containerStatuses | selectattr('name', 'equalto', instance_name + '-controller-task') | map(attribute='ready') | list | first == true
  kubernetes.core.k8s_info:
    kind: Pod
    api_version: v1
    namespace: "{{ namespace }}"
    label_selectors:
      - "app.kubernetes.io/name={{ _scenario_name }}-controller-task"
      - "app.kubernetes.io/managed-by=automationcontroller-operator"
      - "app.kubernetes.io/component=automationcontroller"