---
- name: Set role variables
  ansible.builtin.include_vars:
    file: "{{ role_path }}/vars/main.yml"
    hash_behaviour: replace

- name: Delete PVC 'scenario-1-hub-storage'
  kubernetes.core.k8s:
    api_version: v1
    kind: PersistentVolumeClaim
    name: "{{ _scenario_name }}-hub-file-storage"
    namespace: "{{ _scenario_name }}"
    state: absent

- name: Update AAP custom resource
  kubernetes.core.k8s:
    state: present
    definition:
      kind: AnsibleAutomationPlatform
      apiVersion: aap.ansible.com/v1alpha1
      metadata:
        name: "{{ _scenario_name }}"
        namespace: "{{ namespace }}"
      spec:
        hub:
          file_storage_access_mode: "{{ hub_file_access_mode }}"
          file_storage_size: "{{ hub_file_storage_size }}"
          file_storage_storage_class: "{{ hub_file_storage_class }}"
          storage_type: file

- name: Update Hub custom resource
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: automationhub.ansible.com/v1beta1
      kind: AutomationHub
      metadata:
        name: "{{ _scenario_name }}-hub"
        namespace: "{{ namespace }}"
      spec:
        file_storage_access_mode: "{{ hub_file_access_mode }}"
        file_storage_size: "{{ hub_file_storage_size }}"
        file_storage_storage_class: "{{ hub_file_storage_class }}"
        storage_type: file

# - name: Scale down Hub operator deployment
#   kubernetes.core.k8s:
#     api_version: apps/v1
#     kind: Deployment
#     namespace: "{{ namespace }}"
#     name: "automation-hub-operator-controller-manager"
#     state: present
#     merge_type: merge
#     resource_definition:
#       apiVersion: apps/v1
#       kind: Deployment
#       metadata:
#         name: "automation-hub-operator-controller-manager"
#         namespace: "{{ namespace }}"
#       spec:
#         replicas: 0
#   register: hub_deployment_scale_status

# - name: Scale down gateway operator deployment
#   kubernetes.core.k8s:
#     api_version: apps/v1
#     kind: Deployment
#     namespace: "{{ namespace }}"
#     name: "aap-gateway-operator-controller-manager"
#     state: present
#     merge_type: merge
#     resource_definition:
#       apiVersion: apps/v1
#       kind: Deployment
#       metadata:
#         name: "aap-gateway-operator-controller-manager"
#         namespace: "{{ namespace }}"
#       spec:
#         replicas: 0
#   register: gateway_deployment_scale_status

- name: Delete Deployment 'hub-api'
  kubernetes.core.k8s:
    api_version: apps/v1
    kind: Deployment
    name: "{{ _scenario_name }}-hub-api"
    namespace: "{{ namespace }}"
    state: absent

# - name: Scale up gateway operator deployment
#   kubernetes.core.k8s:
#     api_version: apps/v1
#     kind: Deployment
#     namespace: "{{ namespace }}"
#     name: "aap-gateway-operator-controller-manager"
#     state: present
#     merge_type: merge
#     resource_definition:
#       apiVersion: apps/v1
#       kind: Deployment
#       metadata:
#         name: "aap-gateway-operator-controller-manager"
#         namespace: "{{ namespace }}"
#       spec:
#         replicas: 1
#   register: gateway_deployment_scale_status

- name: Wait for Automation Hub API pod
  register: _hub_pod
  retries: 60
  delay: 15
  until:
    - _hub_pod['resources'] | length
    - _hub_pod['resources'][0].status.containerStatuses | selectattr('name', 'equalto', 'api') | map(attribute='ready') | list | first is defined
    - _hub_pod['resources'][0].status.containerStatuses | selectattr('name', 'equalto', 'api') | map(attribute='ready') | list | first == true
  kubernetes.core.k8s_info:
    kind: Pod
    api_version: v1
    namespace: "{{ namespace }}"
    label_selectors:
      - "app.kubernetes.io/name=automationhub-api"
      - "app.kubernetes.io/instance=automationhub-api-{{ _scenario_name }}-hub"
      - "app.kubernetes.io/component=api"