---

- name: Set role variables
  no_log: "{{ nolog | default(True) }}"
  ansible.builtin.include_vars:
    file: "{{ role_path }}/vars/main.yml"
    hash_behaviour: replace

- name: Set the table
  ansible.builtin.set_fact:
    user_confirmation: "no"

- name: Find the first issue?
  ansible.builtin.pause:
    prompt: |-
      Did you figure out and fix the first issue? There were two issues. 
      (yes or no)
      (Entering yes will fix the lab. Enter no, or wait until you find the issue to fix the lab)
    echo: yes
  register: confirmation_input
  until: confirmation_input.user_input is defined and confirmation_input.user_input | lower == 'yes'
  retries: 99999
  delay: 0

- name: Get UID of the AnsibleAutomationPlatform CR
  kubernetes.core.k8s_info:
    api_version: aap.ansible.com/v1alpha1
    kind: AnsibleAutomationPlatform
    name: "{{ _scenario_name }}-aap"
    namespace: "{{ namespace }}"
  register: aap_cr_info    

- name: "Create the {{ _scenario_name }}-aap-postgres-15 service"
  kubernetes.core.k8s:
    api_version: v1
    kind: Service
    name: "{{ _scenario_name }}-aap-postgres-15"
    namespace: "{{ namespace }}" 
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: "{{ _scenario_name }}-aap-postgres-15"
        namespace: "{{ namespace }}" 
        ownerReferences:
          - apiVersion: aap.ansible.com/v1alpha1
            kind: AnsibleAutomationPlatform
            name: "{{ _scenario_name }}-aap"
            uid: "{{ aap_cr_info.resources[0].metadata.uid }}"
        labels:
          app.kubernetes.io/component: database
          app.kubernetes.io/instance: "postgres-15-{{ _scenario_name }}-aap"
          app.kubernetes.io/managed-by: aap-gateway-operator
          app.kubernetes.io/name: postgres-15
      spec:
        clusterIP: None
        ipFamilies:
          - IPv4
        ports:
          - name: '5432'
            protocol: TCP
            port: 5432
            targetPort: 5432
        internalTrafficPolicy: Cluster
        clusterIPs:
          - None
        type: ClusterIP
        ipFamilyPolicy: SingleStack
        sessionAffinity: None
        selector:
          app.kubernetes.io/component: database
          app.kubernetes.io/instance: "postgres-15-{{ _scenario_name }}-aap"
          app.kubernetes.io/managed-by: aap-gateway-operator
          app.kubernetes.io/name: postgres-15   

- name: Set the table
  ansible.builtin.set_fact:
    second_user_confirmation: "no"

- name: Find the second issue?
  ansible.builtin.pause:
    prompt: |-
      Did you figure out and fix the second issue? There were two issues. 
      (yes or no)
      (Entering yes will fix the lab. Enter no, or wait until you find the issue to fix the lab)
    echo: yes
  register: confirmation_input
  until: confirmation_input.user_input is defined and confirmation_input.user_input | lower == 'yes'
  retries: 99999
  delay: 0                    

- name: Find the current gateway admin secret
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    name: "{{ _scenario_name }}-aap-admin-password"
    namespace: "{{ namespace }}"
  register: admin_password_secret

- name: Decode the 'password' field and set as a fact
  ansible.builtin.set_fact:
    gateway_admin_password: >
      {{ admin_password_secret.resources[0].data.password
          | b64decode 
          | string 
          | trim }}
  when: admin_password_secret.resources | length > 0  

- name: Find gateway pod name
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Pod
    namespace: "{{ namespace }}"
    label_selectors: app.kubernetes.io/component=aap-gateway
  register: gateway_pods
  no_log: "{{ nolog | default(True) }}"    

- name: Find another thing
  ansible.builtin.set_fact:
    extracted_name_raw: >
      {{ gateway_pods.resources
        | selectattr('status.phase', 'equalto', 'Running')
        | map(attribute='metadata.name')
        | first | default('') | string }}
  no_log: "{{ nolog | default(True) }}"

- name: Clean up pod name
  ansible.builtin.set_fact:
    gateway_pod_name: "{{ extracted_name_raw | replace('\n', '') | replace('\r', '') | trim }}"
  no_log: "{{ nolog | default(True) }}"

- name: Fail sometimes
  ansible.builtin.fail:
    msg: "Could not find a running pod with the label 'app=aap-gateway'. Check pod status."
  when: gateway_pod_name is none or gateway_pod_name | length == 0
  no_log: "{{ nolog | default(True) }}"

- name: Run aap-gateway-manage command using the existing admin secret value
  kubernetes.core.k8s_exec:
    namespace: "{{ namespace }}"
    pod: "{{ gateway_pod_name }}"
    container: "api"
    command: aap-gateway-manage update_password --username admin --password {{ gateway_admin_password }}
      # bash -c "echo 'from django.contrib.auth import get_user_model; User = get_user_model(); u=User.objects.get(username=\"admin\"); u.set_password(\"{{ gateway_admin_password }}\"); u.save()' | aap-gateway-manage shell"
  register: command_output
  changed_when: command_output.rc == 0
  no_log: "{{ nolog | default(True) }}"  

# - name: Get Active CSV Name from Subscription
#   kubernetes.core.k8s_info:
#     api_version: operators.coreos.com/v1alpha1
#     kind: Subscription
#     name: "ansible-automation-platform-operator" 
#     namespace: "{{ namespace }}"
#   register: sub_info

# - name: Set Active CSV Name fact
#   ansible.builtin.set_fact:
#     current_csv_name: "{{ sub_info.resources[0].status.installedCSV }}"

# - name: Revert CSV Patch Set Gateway Operator Replicas back to 1
#   ansible.builtin.shell:
#     cmd: >
#       oc patch csv {{ current_csv_name }} -n {{ namespace }} --type='json' 
#       -p='[{"op":"replace", "path":"/spec/install/spec/deployments/0/spec/replicas", "value":1}]'
#   register: csv_revert_status
#   changed_when: csv_revert_status.rc == 0 and ('patched' in csv_revert_status.stdout or 'patched' in csv_revert_status.stderr)
#   failed_when: csv_revert_status.rc != 0

# - name: Scale down Hub operator deployment
#   kubernetes.core.k8s:
#     api_version: apps/v1
#     kind: Deployment
#     namespace: "{{ namespace }}"
#     name: "automation-hub-operator-controller-manager"
#     state: present
#     merge_type: merge
#     resource_definition:
#       apiVersion: apps/v1
#       kind: Deployment
#       metadata:
#         name: "automation-hub-operator-controller-manager"
#         namespace: "{{ namespace }}"
#       spec:
#         replicas: 0
#   register: hub_deployment_scale_status

# - name: Scale up Hub operator deployment
#   kubernetes.core.k8s:
#     api_version: apps/v1
#     kind: Deployment
#     namespace: "{{ namespace }}"
#     name: "automation-hub-operator-controller-manager"
#     state: present
#     merge_type: merge
#     resource_definition:
#       apiVersion: apps/v1
#       kind: Deployment
#       metadata:
#         name: "automation-hub-operator-controller-manager"
#         namespace: "{{ namespace }}"
#       spec:
#         replicas: 1
#   register: hub_deployment_scale_status  

- name: Wait for Automation Hub API pod
  register: _hub_pod
  retries: 60
  delay: 15
  until:
    - _hub_pod['resources'] | length
    - _hub_pod['resources'][0].status.containerStatuses | selectattr('name', 'equalto', 'api') | map(attribute='ready') | list | first is defined
    - _hub_pod['resources'][0].status.containerStatuses | selectattr('name', 'equalto', 'api') | map(attribute='ready') | list | first == true
  kubernetes.core.k8s_info:
    kind: Pod
    api_version: v1
    namespace: "{{ namespace }}"
    label_selectors:
      - "app.kubernetes.io/name=automationhub-api"
      - "app.kubernetes.io/instance=automationhub-api-{{ _scenario_name }}-aap-hub"
      - "app.kubernetes.io/component=api"    