---

- name: Set role variables
  no_log: "{{ nolog | default(True) }}"
  ansible.builtin.include_vars:
    file: "{{ role_path }}/vars/main.yml"
    hash_behaviour: replace

- name: mmm... yes... breaking things
  kubernetes.core.k8s:
    state: patched
    definition:
      apiVersion: aap.ansible.com/v1alpha1
      kind: AnsibleAutomationPlatform
      metadata:
        name: "{{ _scenario_name }}-aap"
        namespace: "{{ namespace }}"
      spec:
        database:
          node_selector:
            "kubernetes.io/os": "not_linux"
  no_log: "{{ nolog | default(True) }}"            

- name: Make sure its broken
  kubernetes.core.k8s:
    api_version: apps/v1
    kind: Deployment
    namespace: "{{ namespace }}"
    name: "{{ _scenario_name }}-aap-gateway"
    state: present
    merge_type: merge
    resource_definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: "{{ _scenario_name }}-aap-gateway"
        namespace: "{{ namespace }}"
      spec:
        replicas: 0
  register: deployment_scale_status
  no_log: "{{ nolog | default(True) }}"  

- name: This will be fun
  kubernetes.core.k8s:
    state: patched
    definition:
      apiVersion: aap.ansible.com/v1alpha1
      kind: AnsibleAutomationPlatform
      metadata:
        name: "{{ _scenario_name }}-aap"
        namespace: "{{ install_namespace }}"
      spec:
        api:
          resource_requirements:
            limits:
              cpu: 1000m
              memory: 500Gi
            requests:
              cpu: 400m
              memory: 500Gi
  no_log: "{{ nolog | default(True) }}"              

- name: Extra Broke
  kubernetes.core.k8s:
    api_version: apps/v1
    kind: Deployment
    namespace: "{{ namespace }}"
    name: "{{ _scenario_name }}-aap-gateway"
    state: present
    merge_type: merge
    resource_definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: "{{ _scenario_name }}-aap-gateway"
        namespace: "{{ namespace }}"
      spec:
        replicas: 1
  register: deployment_scale_status
  no_log: "{{ nolog | default(True) }}"  