---

- name: Set role variables
  no_log: "{{ nolog | default(True) }}"
  ansible.builtin.include_vars:
    file: "{{ role_path }}/vars/main.yml"
    hash_behaviour: replace

- name: Set the table
  ansible.builtin.set_fact:
    user_confirmation: "no"

- name: Find the issue?
  ansible.builtin.pause:
    prompt: |-
      Did you figure out and fix the issues? There were two issues.
      (yes or no)
      (Entering yes will fix the lab. Enter no, or wait until you find the issue to fix the lab)
    echo: yes
  register: confirmation_input
  until: confirmation_input.user_input is defined and confirmation_input.user_input | lower == 'yes'
  retries: 99999
  delay: 0

- name: Find AAP admin password
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    name: "{{ _scenario_name }}-aap-admin-password"
    namespace: "{{ namespace }}"
  register: gateway_secret

- name: Fail if admin password can't be found
  ansible.builtin.fail:
    msg: "Secret 'aap-gateway-admin-password-secret' not found."
  when: gateway_secret.resources | length == 0

- name: Set Admin password fact
  ansible.builtin.set_fact:
    adminpw_string_raw: "{{ gateway_secret.resources[0].data.password | b64decode | string }}"

- name: Clean up admin password fact
  ansible.builtin.set_fact:
    aap_admin_password: "{{ adminpw_string_raw | regex_replace('[^a-zA-Z0-9\\-]', '') | trim }}"

- name: Find admin oauth token
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    name: "{{ _scenario_name }}-aap-gateway-oauth2-token-secret"
    namespace: "{{ namespace }}"
  register: oauth_token_secret

- name: Fail if oauth token is not found
  ansible.builtin.fail:
    msg: "Secret 'aap-gateway-oauth2-token-secret' not found in namespace {{ namespace }}."
  when: oauth_token_secret.resources | length == 0

- name: Set oauth token fact
  ansible.builtin.set_fact:
    token_string_raw: "{{ oauth_token_secret.resources[0].data.token | b64decode | string }}"

- name: Clean up oauth token fact
  ansible.builtin.set_fact:
    aap_oauth2_token: "{{ token_string_raw | regex_replace('[^a-zA-Z0-9\\-]', '') | trim }}"

- name: Get info about AAP Deployment
  kubernetes.core.k8s_info:
    api_version: aap.ansible.com/v1alpha1
    kind: AnsibleAutomationPlatform
    name: "{{ _scenario_name }}-aap"
    namespace: "{{ namespace }}"
  register: aap_cr_info

- name: Set controller_host variable
  ansible.builtin.set_fact:
    controller_host: "{{ aap_cr_info.resources[0].status.URL | default('') }}"
  when: aap_cr_info.resources | length > 0 and
        aap_cr_info.resources[0].status.URL is defined

- name: Fail if url is missing
  ansible.builtin.fail:
    msg: "FATAL: Could not extract the Platform Gateway URL from the AAP CR status (status.URL is missing or empty)."
  when: controller_host | length == 0      

- name: Update Job Template EE
  ansible.controller.job_template:
    controller_host: "{{ controller_host }}"
    controller_oauthtoken: "{{ aap_oauth2_token }}"
    validate_certs: false
    name: "{{ item.name }}"
    description: "Job Template for Summit Troubleshooting Lab {{ item.suffix }}"
    organization: "Default"
    project: "AAP Troubleshooting Demo"
    inventory: "Summit Inventory"
    execution_environment: "Default execution environment"
    playbook: "playbooks/summit-t{{ item.suffix }}.yml"
    job_type: run
    allow_simultaneous: true
    state: present
  loop:
    - { name: "SUMMIT-T4", suffix: 4 }

- name: Log in to AAP, run SUMMIT-T1 through SUMMIT-T4 Job Templates
  ansible.builtin.debug:
    msg: |-
      Log in to AAP, run SUMMIT-T1 through SUMMIT-T4 Job Templates.
      SUMMIT-T4 should run now :D
  no_log: false