---

# Meta Variables
_scenario_name: "scenario-1"

_description: "Describe scenario"

_id_override: 1.2

# Role-specific Variables
scm_project_name: "Demo"
scm_project_url: "https://github.com/demonpig/aap-example-project"

event_stream_name: "54069451-2150-430b-b039-2685340ccb52"
