---
_scenario_name: "scenario-6"
namespace: "{{project_name}}" #""scenario-6"
_id_override: 6

_description: "Ansible Lightspeed Intelligent Assistant (ALIA) Issues"

hub_file_access_mode: ReadWriteMany
hub_file_storage_class: ocs-external-storagecluster-cephfs