---
install_namespace: "{{ project_name }}"
install_channel: 'stable-2.6'
chatbot_model: granite-3-2-8b-instruct
chatbot_token: "{{ alia_token }}"
chatbot_url: https://litellm-prod.apps.maas.redhatworkshops.io/v1