---

install_csv_replicas_gateway: 1
install_csv_replicas_lightspeed: 0
install_csv_replicas_controller: 0
install_csv_replicas_automation_hub: 1
install_csv_replicas_eda: 0
install_csv_replicas_resources: 0