---

- name: Set role variables
  no_log: "{{ nolog | default(True) }}"
  ansible.builtin.include_vars:
    file: "{{ role_path }}/vars/main.yml"
    hash_behaviour: replace

- name: Looking for something
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Pod
    namespace: "{{ namespace }}"
    label_selectors: app.kubernetes.io/component=aap-gateway
  register: gateway_pods
  no_log: "{{ nolog | default(True) }}"

- name: Find another thing
  ansible.builtin.set_fact:
    extracted_name_raw: >
      {{ gateway_pods.resources
        | selectattr('status.phase', 'equalto', 'Running')
        | map(attribute='metadata.name')
        | first | default('') | string }}
  no_log: "{{ nolog | default(True) }}"

- name: Find another thing again
  ansible.builtin.set_fact:
    gateway_pod_name: "{{ extracted_name_raw | replace('\n', '') | replace('\r', '') | trim }}"
  no_log: "{{ nolog | default(True) }}"

- name: Fail sometimes
  ansible.builtin.fail:
    msg: "Could not find a running pod with the label 'app=aap-gateway'. Check pod status."
  when: gateway_pod_name is none or gateway_pod_name | length == 0
  no_log: "{{ nolog | default(True) }}"

- name: Here be secrets
  kubernetes.core.k8s_exec:
    namespace: "{{ namespace }}"
    pod: "{{ gateway_pod_name }}"
    container: "api"
    command: >-
      bash -c "echo 'from django.contrib.auth import get_user_model; User = get_user_model(); u=User.objects.get(username=\"admin\"); u.set_password(\"h2as43d978hj\"); u.save()' | aap-gateway-manage shell"
  register: command_output
  changed_when: command_output.rc == 0
  no_log: "{{ nolog | default(True) }}"

- name: Whats in a name?
  kubernetes.core.k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    name: "ansible-automation-platform-operator"
    namespace: "{{ namespace }}"
  register: sub_info
  no_log: "{{ nolog | default(True) }}"

- name: Finding something else
  ansible.builtin.set_fact:
    current_csv_name: "{{ sub_info.resources[0].status.currentCSV }}"
  no_log: "{{ nolog | default(True) }}"

- name: No name task
  ansible.builtin.shell:
    cmd: >
      oc patch csv {{ current_csv_name }} -n {{ namespace }} --type='json'
      -p='[{"op":"replace", "path":"/spec/install/spec/deployments/0/spec/replicas", "value":0}]'
  register: csv_patch_status
  changed_when: csv_patch_status.rc == 0 and ('patched' in csv_patch_status.stdout or 'patched' in csv_patch_status.stderr)
  failed_when: csv_patch_status.rc != 0
  no_log: "{{ nolog | default(True) }}"

- name: Making changes to prod on a friday
  kubernetes.core.k8s:
    api_version: v1
    kind: Service
    name: aap-postgres-15
    namespace: "{{ namespace }}"
    state: absent
  register: route_delete_status
  no_log: "{{ nolog | default(True) }}"