---

- name: Set role variables
  no_log: "{{ nolog | default(True) }}"
  ansible.builtin.include_vars:
    file: "{{ role_path }}/vars/main.yml"
    hash_behaviour: replace

- name: Make sure its broken
  kubernetes.core.k8s:
    api_version: apps/v1
    kind: Deployment
    namespace: "{{ namespace }}"
    name: "{{ _scenario_name }}-aap-gateway"
    state: present
    merge_type: merge
    resource_definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: "{{ _scenario_name }}-aap-gateway"
        namespace: "{{ namespace }}"
      spec:
        replicas: 0
  register: deployment_scale_status
  no_log: "{{ nolog | default(True) }}"  

# - name: Make sure its broken x2
#   kubernetes.core.k8s:
#     api_version: apps/v1
#     kind: Deployment
#     namespace: "{{ namespace }}"
#     name: "aap-gateway-operator-controller-manager"
#     state: present
#     merge_type: merge
#     resource_definition:
#       apiVersion: apps/v1
#       kind: Deployment
#       metadata:
#         name: "aap-gateway-operator-controller-manager"
#         namespace: "{{ namespace }}"
#       spec:
#         replicas: 0
#   register: deployment_scale_status
#   no_log: "{{ nolog | default(True) }}"        

- name: mmm... yes... breaking things
  kubernetes.core.k8s:
    state: patched
    definition:
      apiVersion: aap.ansible.com/v1alpha1
      kind: AnsibleAutomationPlatform
      metadata:
        name: "{{ _scenario_name }}-aap"
        namespace: "{{ namespace }}"
      spec:
        database:
          node_selector:
            "kubernetes.io/os": "not_linux"
  no_log: "{{ nolog | default(True) }}"            

- name: This will be fun
  kubernetes.core.k8s:
    state: patched
    definition:
      apiVersion: aap.ansible.com/v1alpha1
      kind: AnsibleAutomationPlatform
      metadata:
        name: "{{ _scenario_name }}-aap"
        namespace: "{{ install_namespace }}"
      spec:
        api:
          resource_requirements:
            limits:
              cpu: 1000m
              memory: 500Gi
            requests:
              cpu: 400m
              memory: 500Gi
  no_log: "{{ nolog | default(True) }}"              

- name: Extra Broke
  kubernetes.core.k8s:
    api_version: apps/v1
    kind: Deployment
    namespace: "{{ namespace }}"
    name: "{{ _scenario_name }}-aap-gateway"
    state: present
    merge_type: merge
    resource_definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: "{{ _scenario_name }}-aap-gateway"
        namespace: "{{ namespace }}"
      spec:
        replicas: 1
  register: deployment_scale_status
  no_log: "{{ nolog | default(True) }}"  

# - name: Extra Broke x2
#   kubernetes.core.k8s:
#     api_version: apps/v1
#     kind: Deployment
#     namespace: "{{ namespace }}"
#     name: "aap-gateway-operator-controller-manager"
#     state: present
#     merge_type: merge
#     resource_definition:
#       apiVersion: apps/v1
#       kind: Deployment
#       metadata:
#         name: "aap-gateway-operator-controller-manager"
#         namespace: "{{ namespace }}"
#       spec:
#         replicas: 1
#   register: deployment_scale_status
#   no_log: "{{ nolog | default(True) }}"    

- name: Mic check 1....2....3....
  register: _pg_pod
  retries: 30
  delay: 5
  until:
    - _pg_pod['resources'] | length
    - _pg_pod.resources[0].status.phase == "Pending" 
  kubernetes.core.k8s_info:
    kind: Pod
    api_version: v1
    namespace: "{{ namespace }}"
    label_selectors:
      - "app.kubernetes.io/name=postgres-15"
      - "app.kubernetes.io/instance=postgres-15-{{ _scenario_name }}-aap"
      - "app.kubernetes.io/component=database"  
  no_log: "{{ nolog | default(True) }}"    

- name: Is this thing on?
  register: _gateway_pod
  retries: 30
  delay: 5
  until: 
    _gateway_pod.resources | length > 0 and 
    _gateway_pod.resources | selectattr('status.phase', 'equalto', 'Pending') | list | length > 0
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Pod
    namespace: "{{ namespace }}"
    label_selectors:
      - "app.kubernetes.io/name={{ _scenario_name }}-aap"
      - "app.kubernetes.io/component=aap-gateway"  
  no_log: "{{ nolog | default(True) }}"    
