---

- name: Set role variables
  ansible.builtin.include_vars:
    file: "{{ role_path }}/vars/main.yml"
    hash_behaviour: replace

- name: Create AAP custom resource
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: aap.ansible.com/v1alpha1
      kind: AnsibleAutomationPlatform
      metadata:
        name: "{{ _scenario_name }}-aap"
        namespace: "{{ namespace }}"
      spec:
        eda:
          disabled: true
        route_tls_termination_mechanism: Edge
        redis_mode: standalone
        image_pull_policy: IfNotPresent
        hub:
          disabled: false
          file_storage_access_mode: "{{ hub_file_access_mode }}"
          file_storage_size: "{{ hub_file_storage_size }}"
          file_storage_storage_class: "{{ hub_file_storage_class }}"
          storage_type: file
          content:
            resource_requirements:
              limits:
                cpu: 500m
                memory: 800Mi
              requests:
                cpu: 100m
                memory: 200Mi
          api:
            resource_requirements:
              limits:
                cpu: 1000m
                memory: 1Gi
              requests:
                cpu: 400m
                memory: 500Mi
          worker:
            resource_requirements:
              limits:
                cpu: 1000m
                memory: 1Gi
              requests:
                cpu: 400m
                memory: 500Mi          
        controller:
          disabled: false
  no_log: "{{ nolog | default(True) }}"

- name: Wait for Gateway pod
  register: _gateway_pod
  retries: 60
  delay: 20
  until:
    - _gateway_pod['resources'] | length
    - _gateway_pod['resources'][0].status.containerStatuses | selectattr('name', 'equalto', 'api') | map(attribute='ready') | list | first is defined
    - _gateway_pod['resources'][0].status.containerStatuses | selectattr('name', 'equalto', 'api') | map(attribute='ready') | list | first == true
  kubernetes.core.k8s_info:
    kind: Pod
    api_version: v1
    namespace: "{{ namespace }}"
    label_selectors:
      - "app.kubernetes.io/name={{ _scenario_name }}-aap"
      - "app.kubernetes.io/managed-by=aap-operator"
      - "app.kubernetes.io/component=aap-gateway"  

- name: Wait for Automation Controller pod
  register: _controller_pod
  retries: 60
  delay: 20
  until:
    - _controller_pod['resources'] | length
    - _controller_pod['resources'][0].status.containerStatuses | selectattr('name', 'equalto', _scenario_name + '-aap-controller-task') | map(attribute='ready') | list | first is defined
    - _controller_pod['resources'][0].status.containerStatuses | selectattr('name', 'equalto', _scenario_name + '-aap-controller-task') | map(attribute='ready') | list | first == true
  kubernetes.core.k8s_info:
    kind: Pod
    api_version: v1
    namespace: "{{ namespace }}"
    label_selectors:
      - "app.kubernetes.io/name={{ _scenario_name }}-aap-controller-task"
      - "app.kubernetes.io/managed-by=automationcontroller-operator"
      - "app.kubernetes.io/component=automationcontroller"

- name: Wait for Automation Hub API pod
  register: _hub_pod
  retries: 60
  delay: 15
  until:
    - _hub_pod['resources'] | length
    - _hub_pod['resources'][0].status.containerStatuses | selectattr('name', 'equalto', 'api') | map(attribute='ready') | list | first is defined
    - _hub_pod['resources'][0].status.containerStatuses | selectattr('name', 'equalto', 'api') | map(attribute='ready') | list | first == true
  kubernetes.core.k8s_info:
    kind: Pod
    api_version: v1
    namespace: "{{ namespace }}"
    label_selectors:
      - "app.kubernetes.io/name=automationhub-api"
      - "app.kubernetes.io/instance=automationhub-api-{{ _scenario_name }}-aap-hub"
      - "app.kubernetes.io/component=api"

- name: Wait for AAP CR to be Ready and URL to be Populated
  kubernetes.core.k8s_info:
    api_version: aap.ansible.com/v1alpha1
    kind: AnsibleAutomationPlatform
    name: "{{ _scenario_name }}-aap"
    namespace: "{{ namespace }}"
  register: aap_status
  retries: 80
  delay: 10
  until: 
    aap_status.resources | length > 0 and
    aap_status.resources[0].status.conditions | 
      selectattr('type', 'equalto', 'Successful') | 
      selectattr('status', 'equalto', 'True') | 
      list | length > 0 and
    aap_status.resources[0].status.URL is defined and 
    aap_status.resources[0].status.URL | length > 0

- name: Display Final URL
  ansible.builtin.debug:
    msg: "Ansible Automation Platform is Ready. Access URL: {{ aap_status.resources[0].status.URL }}"
  when: aap_status is success        